import { type job, JobStatus } from "./types/job";

const jobs: job[] = [
  {
    id: crypto.randomUUID(),
    title: "Frontend Developer",
    company: "Vertex Digital",
    location: "London, UK",
    appliedDate: "2026-08-22",
    offerDate: "",
    interviewedDate: "",
    rejectedDate: "",
    url: "https://example.com",
    status: JobStatus.applied,
    notes: "React and TypeScript development. Working with a small frontend team building customer-facing web applications.",
    rating: 5,
  },
  {
    id: crypto.randomUUID(),
    title: "Junior Software Developer",
    company: "Northstar Technologies",
    location: "Manchester, UK",
    appliedDate: "2026-08-20",
    offerDate: "",
    interviewedDate: "",
    rejectedDate: "",
    url: "https://example.com",
    status: JobStatus.applied,
    notes: "Entry-level software development role with opportunities to work across frontend and backend systems.",
    rating: 4,
  },
  {
    id: crypto.randomUUID(),
    title: "Web Developer",
    company: "Brightline Systems",
    location: "Birmingham, UK",
    appliedDate: "2026-08-18",
    offerDate: "",
    interviewedDate: "",
    rejectedDate: "",
    url: "https://example.com",
    status: JobStatus.applied,
    notes: "Full-stack web development using JavaScript and Node.js.",
    rating: 5,
  },
  {
    id: crypto.randomUUID(),
    title: "Graduate Software Engineer",
    company: "Apex Solutions",
    location: "Warwick, UK",
    appliedDate: "2026-08-14",
    offerDate: "",
    interviewedDate: "2026-08-21",
    rejectedDate: "",
    url: "https://example.com",
    status: JobStatus.interviewed,
    notes: "Graduate engineering programme with a focus on software development and cloud technologies.",
    rating: 5,
  },
  {
    id: crypto.randomUUID(),
    title: "Full Stack Developer",
    company: "Cloudbridge",
    location: "Leeds, UK",
    appliedDate: "2026-08-10",
    offerDate: "",
    interviewedDate: "2026-08-19",
    rejectedDate: "",
    url: "https://example.com",
    status: JobStatus.interviewed,
    notes: "Building and maintaining full-stack applications using modern JavaScript frameworks.",
    rating: 4,
  },
  {
    id: crypto.randomUUID(),
    title: "Software Engineer",
    company: "TechCore",
    location: "Nottingham, UK",
    appliedDate: "2026-07-28",
    offerDate: "2026-08-18",
    interviewedDate: "2026-08-07",
    rejectedDate: "",
    url: "https://example.com",
    status: JobStatus.offered,
    notes: "Software engineering position working on internal platforms and customer-facing services.",
    rating: 5,
  },
  {
    id: crypto.randomUUID(),
    title: "Graduate AI Engineer",
    company: "DigitalWorks",
    location: "Bristol, UK",
    appliedDate: "2026-08-02",
    offerDate: "",
    interviewedDate: "",
    rejectedDate: "2026-08-15",
    url: "https://example.com",
    status: JobStatus.rejected,
    notes: "Graduate web development position focused on building responsive web applications.",
    rating: 3,
  },
  {
    id: crypto.randomUUID(),
    title: "Software Developer",
    company: "DataSphere",
    location: "London, UK",
    appliedDate: "2026-07-25",
    offerDate: "",
    interviewedDate: "",
    rejectedDate: "2026-08-08",
    url: "https://example.com",
    status: JobStatus.rejected,
    notes: "Software development role working with APIs, databases and internal business applications.",
    rating: 2,
  },
];

export default jobs;
